import math
print("---PREMIER ALIGNEMENT---")
a1s1 = input("Entrer le S du point 1 :")
a1z1 = input("Entrer le Z du point 1 :")
a1s2 = input("Entrer le S du point 2 :")
a1z2 = input("Entrer le Z du point 2 :")
a1ds = float(a1s2) - float(a1s1)
print ("ds :"),round(a1ds,3),("m")
a1dz = float(a1z2) - float(a1z1)
print ("dz :"),round(a1dz,3),("m")
a1p = (float(a1dz) / float(a1ds))
print("pente :"),a1p*100,("%")
print("")
print("---DEUXIEME ALIGNEMENT---")
a2s1 = input("Entrer le S du point 1 :")
a2z1 = input("Entrer le Z du point 1 :")
a2s2 = input("Entrer le S du point 2 :")
a2z2 = input("Entrer le Z du point 2 :")
a2ds = float(a2s2) - float(a2s1)
print("ds :"),round(a2ds,3),("m")
a2dz = float(a2z2) - float(a2z1)
print("dz :"),round(a2dz,3),("m")
a2p = (float(a2dz) / float(a2ds))
print("pente :"),round(a2p,3)*100,("%")
print("")
print("---PARABOLE---")
rp = input("Entrer le rayon parabolique (negatif si angle saillant) :")
print("")
print("---POINTS CARACTERISTIQUES---")
g1i = (math.atan2(float(a1ds),float(a1dz))*200/math.pi)%400
g2i = (math.atan2(float(a2ds),float(a2dz))*200/math.pi+200)%400
sI = float(a1s1)+(((float(a1s1)-float(a2s1))-(float(a1z1)-float(a2z1))*math.tan(float(g2i)*math.pi/200))/(math.tan(float(g2i)*math.pi/200)-math.tan(float(g1i)*math.pi/200)))*math.tan(float(g1i)*math.pi/200)
print("S du point d'intersection des 2 alignements :"),round(sI,3),("m")
zI = float(a1z1)+((float(a1s1)-float(a2s1))-(float(a1z1)-float(a2z1))*math.tan(float(g2i)*math.pi/200))/(math.tan(float(g2i)*math.pi/200)-math.tan(float(g1i)*math.pi/200))
print("Z du point d'intersection des 2 alignements :"),round(zI,3),("m")
dsT1T2 = float(rp)*(float(a2p)-float(a1p))
dsT1i = float(dsT1T2)/2
sT1 = float(sI)-float(dsT1i)
print("S du premier point de tangence :"),round(sT1,3),("m")
zT1 = float(zI)-float(dsT1i)*float(a1p)
print("Z du premier point de tangence :"),round(zT1,3),("m")
sT2 = float(sI)+float(dsT1i)
print("S du deuxième point de tangence :"),round(sT2,3),("m")
zT2 = float(zI)+float(dsT1i)*float(a2p)
print("Z du deuxième point de tangence"),round(zT2,3),("m")
dsST1 = float(a1p)*float(rp)
dzST1 = ((float(a1p)*float(rp))**2)/(2*float(rp))
sS = float(sT1)-float(dsST1)
print("S du sommet de la parabole"),round(sS,3),("m")
zS = float(zT1)-float(dzST1)
print("Z du sommet de la parabole"),round(zS,3),("m")
print("")
print("---IMPLANTATION---")
sN =("sN")
while sN !="":
  print("")
  sN = input("Entrer le S d'un point quelconque n :")
  zN = float(zS)+(((float(sN)-float(sS))**2)/(2*float(rp)))
  print("Z d'un point quelconque n :"),round(zN,3),("m")
